# Generated by Django 3.0.7 on 2020-06-20 09:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=models.SlugField(blank=True, default='', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.CharField(blank=True, help_text='Automatiquement le superuser', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterModelTable(
            name='entry',
            table='cms_entry',
        ),
    ]
